<?php //Do not edit this file by hand, it will be overwritting by the configuration utility. 
$MILEAGELOG_CONFIG['minimum_report_level'] = '9';
$MILEAGELOG_CONFIG['minimum_see_level'] = '7';
$MILEAGELOG_CONFIG['minimum_edit_level'] = '9';
$MILEAGELOG_CONFIG['cost_per_unit'] = '0.37';
$MILEAGELOG_CONFIG['show_purpose_task'] = '1';
$MILEAGELOG_CONFIG['show_purpose_helpdesk'] = '1';
$MILEAGELOG_CONFIG['show_purpose_note'] = '1';
?>